version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "browser",
    "mongo"
  ]

[[analyzers]]
name = "sql"

[[analyzers]]
name = "test-coverage"