-- AlterTable
ALTER TABLE "UserLeaveTable" ALTER COLUMN "usedLeaves" SET DEFAULT 0,
ALTER COLUMN "usedLeaves" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "availableLeave" SET DEFAULT 30,
ALTER COLUMN "availableLeave" SET DATA TYPE DOUBLE PRECISION;
